// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EventsController from "./events_controller"
application.register("events", EventsController)

import MapsController from "./maps_controller"
application.register("maps", MapsController)

import SearchFormController from "./search_form_controller"
application.register("search-form", SearchFormController)

import SlotsController from "./slots_controller"
application.register("slots", SlotsController)
