inherit_mode:
  merge:
    - Exclude

require:
  - standard

inherit_gem:
  standard: config/base.yml

inherit_from:
  - .rubocop/rails.yml
  - .rubocop/rspec.yml
  - .rubocop_todo.yml
  - .rubocop/strict.yml
  - .rubocop-mine.yml

AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  Exclude:
    - bin/*
    - app/models/role.rb
    - db/**/*.rb
    - node_modules/*
    - vendor/*
    - tmp/*
    - log/*
    - coverage/*
    - .bundle/*
    - .git/*
